### ISSUE TITLE
Using

### ISSUE THREAD

**Issue by e-dant** [cschreib/snatch#23]
The intended and/or best way to use this project isn't clear. 

There seem to be rules in the cmake files to make this a header-only library. 

It also looks like a library. 

Are there any link options needed? Catch had something odd about build & link options depending on where the test's `main` was. Is the same true here?

Anyway, thank you for your work.

**Comment by cschreib** [comment]
Hello and thank you for your interest in _snatch_! You're right that this information is currently missing in the README, I'll see about adding that in the on-going PR. In the meantime I'll answer your questions here:

> There seem to be rules in the cmake files to make this a header-only library.

There are indeed. There is already some information on this in the [README](https://github.com/cschreib/snatch#header-only-build). The recommended and "default" is to use _snatch_ as a regular library, with a compiled `.a`/`.lib` file and a few headers. If you use CMake, you can do the canonical `target_link_library(your_test_app PRIVATE snatch::snatch)` and it will all work. But the CMake scripts also produce a header-only version if that is what you prefer. I plan to add this header-only version as a downloadable artifact to the coming release, so you don't have to use CMake at all (I've seen this requested here and there).

> Are there any link options needed? Catch had something odd about build & link options depending on where the test's main was. Is the same true here?

As with most test frameworks, there is a bit of configuration around "who provides `main()`". This is also described in the [README](https://github.com/cschreib/snatch#using-your-own-main-function). The default is that _snatch_ defines it for you, but you can change this if you need your own `main()`.

**Comment by cschreib** [comment]
This commit https://github.com/cschreib/snatch/pull/22/commits/3b6c0e2d15b5fc818c755c14b50bc1f6accdabaa added some examples on how to use the library with CMake. Let me know if that helps, or if you need something else.

**Comment by e-dant** [comment]
Thank you very much! Great explainer, Cheers.

**Comment by cschreib** [comment]
No worries. I will close this issue, but please reopen it if you still have issues with setting up CMake, builds, etc.

**Comment by e-dant** [comment]
Hi there. Been trying to figure out this error:

``` error: use of undeclared identifier 'SNATCH_CURRENT_TEST'```

Have you seen this before?

**Comment by cschreib** [comment]
I suspect this happens because you are trying to use a test macro, like `REQUIRE` or `CHECK`, outside of a `TEST_CASE`. These macros must be used directly inside a test, they cannot be used in other functions.

If the above doesn't help, it would help me to share the full code that triggers the problem.

**Comment by e-dant** [comment]
Ah, yes I have been doing that.

I might be able to get the code up next weekend. I'm attempting to use it on [Watcher](https://github.com/e-dant/watcher/tree/next) instead of Catch.

**Comment by cschreib** [comment]
FYI, as of c6d356f1b22fe4b739a47c0acbdb7a4c36598da1, the test macros can be used in other functions, so you should be able to use _snatch_ in your project without changing the tests.
