### ISSUE TITLE
Add support for TEST_CASE without tags

### ISSUE THREAD

**Issue by horenmar** [cschreib/snatch#42]
There is no good reason to require tags on small examples, but currently this does not compile

```cpp
#include <snatch/snatch.hpp>

TEST_CASE("spaceshippy") {};
```

**Comment by cschreib** [comment]
Hi and thanks for the feedback! I'll add this to the backlog for the upcoming v1.0 release; this is supported in _Catch2_ so it makes sense for us to support it as well to ease portability.
